### ISSUE TITLE
Pink textures when using resource pack

### ISSUE THREAD

**Issue by Xuerian** [octarine-noise/BetterFoliage#112]
We discussed this when you came to help on https://github.com/asiekierka/FoamFix/issues/5

In [this comment](https://github.com/asiekierka/FoamFix/issues/5#issuecomment-266206805), after your check, I confirmed that it occurs with only Forge, BetterFoliage, and a resource pack.

How should I go about determining if the texture pack is faultily designed, or if there is an issue occurring in BetterFoliage?

**Comment by octarine-noise** [comment]
As it turns out, it's simple. The grass texture of Pixel Perfection isn't _quite_ black & white enough, and BF thinks it should use the texture's natural color (slightly pink) instead of the biome color.

Raise the option "Short Grass / Saturation threshold" to 0.2 and it behaves correctly. It seems I set the default a bit too low - but too high a value runs the risk of the opposite issue happening (blocks being colorized when they shouldn't).
