### ISSUE TITLE
Most leaves and grass grey after update to 1.10.2-2.1.10

### ISSUE THREAD

**Issue by Psy-Virus** [octarine-noise/BetterFoliage#150]
Hey there,
after an update to version `BetterFoliage-MC1.10.2-2.1.10.jar` everything related to better foliage leaves and grass seems to be grey... Reverting to an older version fixes it.
Here you get a screen shot

![2017-09-10_04 31 27](https://user-images.githubusercontent.com/6222200/30245664-5ac946bc-95e1-11e7-816e-942a458a8a69.png)

thanks in advance!

**Comment by Scratchman** [comment]
I'm only seeing this issue with Natura, Forestry and IC2 rubber trees.

![2017-09-10_16 36 42](https://user-images.githubusercontent.com/5376586/30254045-dfd7fc58-9646-11e7-955f-2471524a6fb9.png)

**Comment by WesCook** [comment]
I can also confirm the issue with the latest 1.10.2 version.

![2017-09-10_23 29 13](https://user-images.githubusercontent.com/792101/30261117-ed026678-967f-11e7-90df-0ba8c09bca18.png)

Hooray for fuzzy trees

**Comment by octarine-noise** [comment]
The problem seems to be my integration code for Optifine custom colors. For now, if you turn that off (under video settings / quality) it's fine.

**Comment by Vampsku11** [comment]
This is an issue with Better Foliage. I have tested with Optifine versions 1.10.2_HD_U_D4 to 1.10.2_HD_U_E3, Forge versions 1.10.2-12.18.3.2185 to 1.10.2-12.18.3.2477, and Better Foliage versions 1.10.2-2.1.3 to 1.10.2-2.1.10 on a fresh install of Minecraft. The issue can be recreated with any Forge version, any Optifine version, and specifically Better Foliage version 1.10.2-2.1.10. Any other version of Better Foliage displays the grass the correct color. Something was changed in Better Foliage 1.10.2-2.1.10 that does not agree with any existing versions of Optifine.

**Comment by tenten8401** [comment]
Can confirm this is an issue, it's making some of my grass grey as well. Removing BetterFoliage or disabling Smooth Lighting seem to fix the issue.
![Image](https://cdn.discordapp.com/attachments/291616748392677386/361177534949359617/unknown.png)

**Comment by LiskoSlayer63** [comment]
Can confirm this too, it happens if using "swamp colors" in Optifine's quality settings or "connected textures" in Better Foliage's settings. Turning "swamp colors" off fixes the "growing" grass (generated top of grass blocks) and basically everything else according to this problem. Turning off the "connected textures" fixes only grass block colors. I uploaded a couple of images from "flat" map.

**Swamp colors OFF**
![2017-10-01_00 44 30](https://user-images.githubusercontent.com/10125529/31049771-1ff55d60-a643-11e7-979e-6795afbfb1af.png)

**Swamp colors ON**
![2017-10-01_00 44 46](https://user-images.githubusercontent.com/10125529/31049770-1ff1ab8e-a643-11e7-9130-8df332e136dc.png)

**Comment by octarine-noise** [comment]
I seem to have derped up the last release. Only the 1.10.2 version has this issue.
It happens if you have Optifine custom colors enabled, but the block does not have colors defined for it (no custom colors in your resource pack, or modded block).

Fixed in 2.1.11

**Comment by WesCook** [comment]
Nice work!  :)
