### ISSUE TITLE
Improve error reporting if forgelin is missing.

### ISSUE THREAD

**Issue by za3k** [octarine-noise/BetterFoliage#247]
Thanks for the great mod btw!

On startup, this just crashes without forgelin, and the error message is not easy to figure out. Other mods with a dependency on coremores (for example, see Bountiful which also depends on forgelin) display an error message indicating what mod is needed at what version--I think this is probably some forge dependency system.

**Comment by octarine-noise** [comment]
Unfortunately, it's not possible for technical reasons.

BetterFoliage does declare Forgelin as a dependency, but it's also a coremod (which is necessary to hook deep into the MC rendering system), and the coremod part is also written in Kotlin. Because of the way FML/Forge loads coremods, parts of BetterFoliage are evaluated and loaded (crashing the game without Forgelin) _well_ before Forge has a chance to evaluate dependencies and report any discrepancies.
The only possible solutions I can think of would be to
- log something very prominent and visible to the console if Forgelin is not detected, which I don't want to do, or
- write the coremod part in Java, which I REALLY don't want to do
