### ISSUE TITLE
Strange shading with Optifine and SEUS shaders

### ISSUE THREAD

**Issue by GordonHollow** [octarine-noise/BetterFoliage#327]
After installing BetterFoliage some blocks go brighter than other. All affected blocks are not in the list of features that BF adds
See pic

http://linkme.ufanet.ru/images/46e74df714fbdf91e26468afe913f8ed.png

Sand is dark, sandstone is very bright, thats some lighting conflict

**Comment by octarine-noise** [comment]
Yeah, I see it. Sandstone is actually fine, it's the sand that is too dark.

BF does change rendering for sand, actually, because there's a possibility that it will have coral on it (if underwater).
After a bit of investigation, it does happen with dirt too, but it's just not as noticeable.
Shouldn't bee too difficult to fix.

**Comment by GordonHollow** [comment]
yes, after fly over the world i see that problem with sand
for dirt i can't see any changes
if i turn off coral - it fixes problem maybe?

**Comment by octarine-noise** [comment]
No, it won't. And after looking at it a bit more, it's worse than I though. If you build a large flat wall of sand, and start placing solid blocks (like sandstone) against it, things get really weird.
I know *where* I screwed up, but not yet *what*.

**Comment by GordonHollow** [comment]
Well, i has sand walls in my base, with sandstone borders - and it weird
Okay, just wait for fixes

**Comment by octarine-noise** [comment]
Fixed in 2.6.3

**Comment by GordonHollow** [comment]
Have this in 2.6.4 again T_T
downgrade to 2.6.3 only solution? this version work better
